### ISSUE TITLE
nucleof334 debugging problem

### ISSUE THREAD

**Issue by soson** [rust-embedded/cortex-m-semihosting#24]
i am following rust tutorial https://rust-embedded.github.io/bookshelf/book/start/hardware.html to start with embedded programming. 

my hardware is NUCLEOF334R8 with STM32F334R8T6 
i am running into problem with debugging against openocd when running simple "Hello world".

```gdb> target remote :3333```

results into this error:

`cortex_m_semihosting::hio::HStderr::write_all (
    self=0x80002eb, buffer=...)
    at /home/soni/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-semihosting-0.3.1/src/hio.rs:48
48	    open(":tt\0", nr::open::W_APPEND).map(|fd| HStderr { fd }`

your help would be appreciated

thanks

**Comment by therealprof** [comment]
@soson This is not really an error. Have you enabled semihosting via `monitor arm semihosting enable`?

**Comment by soson** [comment]
thanks for your help. running 

`gdb> monitor arm semihosting enable`

`"monitor" command not supported by this target`

this is strange, because i have installed ubuntu 16.04 gdb package suggested by tutorial.

anyway thanks, i will investigate further

**Comment by therealprof** [comment]
Err, you're using an **ARM** gdb, right? The regular ubuntu gdb will not do.

**Comment by therealprof** [comment]
Typically you'd start that with `arm-none-eabi-gdb`, not just `gdb`.

**Comment by soson** [comment]
yes, i am using `arm-none-eabi-gdb`

**Comment by japaric** [comment]
> "monitor" command not supported by this target

As indicated in the book you have to run `monitor arm semihosting enable` *after* `target remote :3333`.

**Comment by korken89** [comment]
This is almost 1 year old, closing issue, reopen if needed

**Comment by ryankurte** [comment]
idk how related but i get the same message from `gdb-multiarch` with the example project (which is installed in as `gdb-arm-none-eabi` in buster) :-/

```
> gdb-multiarch -q target/thumbv7em-none-eabi/debug/test-app 
Reading symbols from target/thumbv7em-none-eabi/debug/test-app ...done.
(gdb) target extended-remote :3333
Remote debugging using :3333
0x08006280 in ?? ()
(gdb) break main
Breakpoint 1 at 0x4d4: file src/main.rs, line 19.
(gdb) 
Note: breakpoint 1 also set at pc 0x4d4.
Breakpoint 2 at 0x4d4: file src/main.rs, line 19.
(gdb) monitor arm semihosting enable
Target does not support this command.
```

_edit: same with [arm-none-eabi-gdb](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads)_

_second edit: need to invoke openocd not st-util, fixed now_
