### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by bofh** [rust-embedded/cortex-m-semihosting#29]
Hello,

While going trough tutorial I’ve encountered the following problems:
* cargo generate is used, but installation step for it is missing;
* in order to run example on [nucleo-f303k8](https://www.st.com/en/evaluation-tools/nucleo-f303k8.html) you need to change values in memory.x to [correct ones](
https://gist.github.com/bofh/fc9416830bf16123aa33909b5fe7c499) or else your debug session will always end in PanicHandler.

The second one is quite hostile for beginners.

**Comment by japaric** [comment]
Thanks for the report. This issue has been filled in the wrong repository. I'm moving it to the book repository: https://github.com/rust-embedded/book/issues/125
