### ISSUE TITLE
open() must be called for stdin/stdout/stderr; FDs may not be 0/1/2

### ISSUE THREAD

**Issue by alexisvl** [rust-embedded/cortex-m-semihosting#5]
cortex-m-semihosting never initializes stdin, stdout, and stderr with `open()`. As such, it never hears from gdb that the file descriptors being used for those are not the traditional 0/1/2 (in my case, gdb is giving out 1/2/3), resulting in the wrong stream being used.

This works for me:

    let _stdin = unsafe{ syscall!(OPEN, ":tt".as_bytes().as_ptr(), 0, 3) };
    let _stdout = unsafe{ syscall!(OPEN, ":tt".as_bytes().as_ptr(), 4, 3) };
    let _stderr = unsafe{ syscall!(OPEN, ":tt".as_bytes().as_ptr(), 8, 3) };

    let buffer = "Hello, world!\n";
    unsafe{ syscall!(WRITE, _stdout, buffer.as_ptr(), buffer.len()) };

We need something akin to newlib's `initialise_monitor_handles` to actually send the OPEN syscalls and record the file descriptors in use.

**Comment by zargony** [comment]
Great find! I was guessing something like this as the reason for my problems in #4. I also tried to open stdout manually but it still failed to write. I guess I missed that open returned different numbers than usual.

Indeed newlib's `initialise_monitor_handles` [does the same](https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=libgloss/arm/syscalls.c;h=0ccad215cdb436cf3ff669038077e773bb35cbe7;hb=9d32147e35464893987d72ffae6d900dec5f9106#l134), it opens stdin/stdout/stderr handles and remembers them. But it also has an additional indirection that ensures that 0, 1 and 2 map to these handles (`openfiles` lookup table). However I'm not sure if we'd want the same. It would be nice to have standard file numbers, but it would also bloat things up a little.

**Comment by alexisvl** [comment]
My PR adds functions `get_stdout()` and `get_stderr()` which return the FDs, which provides equivalent functionality. I don't like the idea of enabling code that assumes the FDs, especially given that none of the functions in this package are `extern "C"` so we're not trying to support existing C code.

**Comment by dhylands** [comment]
I just ran into this as well using my Black Magic Probe. Applying #7 and adding a call to open_streams makes semihosting work.

**Comment by schodet** [comment]
What about making open_streams be called automatically on first write?
